app = "bigcitylife"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 500

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

